language: c

env:
  matrix:
    - TF_VERSION=0.8.6
    - TF_VERSION=0.7.13

before_install:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-TRAVIS_BRANCH}
  - curl -o- -L https://raw.githubusercontent.com/freeletics-engineering/terraform_travis_tests/${BRANCH}/install.sh | sh -s -- ${BRANCH} ${PWD}
